-- DEPRECATED SCHEMA ARTIFACT
--
-- Do NOT apply this file to production.
-- The production database is empty and now uses a migration baseline model:
--   001_initial_schema.sql
--   002_contract_hardening.sql
--
-- This file is retained only as a historical compatibility marker so an older
-- deployment workflow cannot silently become the source of truth.
--
-- Canonical contracts:
--   tickets.description
--   ticket_messages.message (intentional history-content field)
--   payments.user_id, amount, currency, status, proof_path,
--   payments.verification_notes, verified_by, verified_at, created_at, updated_at
